name: govvy
description: A local government transparency app connecting citizens with their representatives.

# Publication information
publish_to: 'none' # Do not publish to pub.dev

# App version information
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # State management
  provider: ^6.0.5
  # UI components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  # Data handling
  http: ^1.1.0
  shared_preferences: ^2.2.0
  archive: ^3.4.9
  # Location services
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  # Utils
  url_launcher: ^6.1.12
  intl: ^0.20.2
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_remote_config: ^5.4.3
  csv: ^5.0.2
  path_provider: ^2.1.1
  
  firebase_analytics: ^11.4.5
  universal_html: ^2.2.4
  flutter_dotenv: ^5.2.1
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/.env
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/data/csvs/
    # State-specific CSV directories
    - assets/data/csvs/AK/2025-2026_34th_Legislature/csv/
    - assets/data/csvs/AL/2025-2025_Regular_Session/csv/
    - assets/data/csvs/AR/2025-2025_95th_General_Assembly/csv/
    - assets/data/csvs/AZ/2025-2025_Fifty-seventh_Legislature_1st_Regular/csv/
    - assets/data/csvs/CA/2025-2026_Regular_Session/csv/
    - assets/data/csvs/CO/2025-2025_Regular_Session/csv/
    - assets/data/csvs/CT/2025-2025_General_Assembly/csv/
    - assets/data/csvs/FL/2025-2025_Regular_Session/csv/
    - assets/data/csvs/GA/2025-2026_Regular_Session/csv/
    - assets/data/csvs/HI/2025-2025_Regular_Session/csv/
    - assets/data/csvs/IA/2025-2026_91st_General_Assembly/csv/
    - assets/data/csvs/IL/2025-2026_104th_General_Assembly/csv/
    - assets/data/csvs/IN/2025-2025_Regular_Session/csv/
    - assets/data/csvs/KS/2025-2026_Regular_Session/csv/
    - assets/data/csvs/KY/2025-2025_Regular_Session/csv/
    # Explicitly include individual CSV files for Florida and Georgia
    - assets/data/csvs/FL/2025-2025_Regular_Session/csv/bills.csv
    - assets/data/csvs/FL/2025-2025_Regular_Session/csv/people.csv
    - assets/data/csvs/FL/2025-2025_Regular_Session/csv/sponsors.csv
    - assets/data/csvs/FL/2025-2025_Regular_Session/csv/history.csv
    - assets/data/csvs/GA/2025-2026_Regular_Session/csv/bills.csv
    - assets/data/csvs/GA/2025-2026_Regular_Session/csv/people.csv
    - assets/data/csvs/GA/2025-2026_Regular_Session/csv/sponsors.csv
    - assets/data/csvs/GA/2025-2026_Regular_Session/csv/history.csv